// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: scheme.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_scheme_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_scheme_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_scheme_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_scheme_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[7]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_scheme_2eproto;
namespace esw {
class Location;
class LocationDefaultTypeInternal;
extern LocationDefaultTypeInternal _Location_default_instance_;
class OneToAll;
class OneToAllDefaultTypeInternal;
extern OneToAllDefaultTypeInternal _OneToAll_default_instance_;
class OneToOne;
class OneToOneDefaultTypeInternal;
extern OneToOneDefaultTypeInternal _OneToOne_default_instance_;
class Request;
class RequestDefaultTypeInternal;
extern RequestDefaultTypeInternal _Request_default_instance_;
class Reset;
class ResetDefaultTypeInternal;
extern ResetDefaultTypeInternal _Reset_default_instance_;
class Response;
class ResponseDefaultTypeInternal;
extern ResponseDefaultTypeInternal _Response_default_instance_;
class Walk;
class WalkDefaultTypeInternal;
extern WalkDefaultTypeInternal _Walk_default_instance_;
}  // namespace esw
PROTOBUF_NAMESPACE_OPEN
template<> ::esw::Location* Arena::CreateMaybeMessage<::esw::Location>(Arena*);
template<> ::esw::OneToAll* Arena::CreateMaybeMessage<::esw::OneToAll>(Arena*);
template<> ::esw::OneToOne* Arena::CreateMaybeMessage<::esw::OneToOne>(Arena*);
template<> ::esw::Request* Arena::CreateMaybeMessage<::esw::Request>(Arena*);
template<> ::esw::Reset* Arena::CreateMaybeMessage<::esw::Reset>(Arena*);
template<> ::esw::Response* Arena::CreateMaybeMessage<::esw::Response>(Arena*);
template<> ::esw::Walk* Arena::CreateMaybeMessage<::esw::Walk>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace esw {

enum Response_Status : int {
  Response_Status_OK = 0,
  Response_Status_ERROR = 1,
  Response_Status_Response_Status_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  Response_Status_Response_Status_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool Response_Status_IsValid(int value);
constexpr Response_Status Response_Status_Status_MIN = Response_Status_OK;
constexpr Response_Status Response_Status_Status_MAX = Response_Status_ERROR;
constexpr int Response_Status_Status_ARRAYSIZE = Response_Status_Status_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* Response_Status_descriptor();
template<typename T>
inline const std::string& Response_Status_Name(T enum_t_value) {
  static_assert(::std::is_same<T, Response_Status>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function Response_Status_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    Response_Status_descriptor(), enum_t_value);
}
inline bool Response_Status_Parse(
    const std::string& name, Response_Status* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<Response_Status>(
    Response_Status_descriptor(), name, value);
}
// ===================================================================

class Request PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:esw.Request) */ {
 public:
  inline Request() : Request(nullptr) {};
  virtual ~Request();

  Request(const Request& from);
  Request(Request&& from) noexcept
    : Request() {
    *this = ::std::move(from);
  }

  inline Request& operator=(const Request& from) {
    CopyFrom(from);
    return *this;
  }
  inline Request& operator=(Request&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Request& default_instance();

  enum MsgCase {
    kWalk = 1,
    kOneToOne = 2,
    kOneToAll = 3,
    kReset = 4,
    MSG_NOT_SET = 0,
  };

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Request* internal_default_instance() {
    return reinterpret_cast<const Request*>(
               &_Request_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Request& a, Request& b) {
    a.Swap(&b);
  }
  inline void Swap(Request* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Request* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Request* New() const final {
    return CreateMaybeMessage<Request>(nullptr);
  }

  Request* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Request>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Request& from);
  void MergeFrom(const Request& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Request* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "esw.Request";
  }
  protected:
  explicit Request(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_scheme_2eproto);
    return ::descriptor_table_scheme_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kWalkFieldNumber = 1,
    kOneToOneFieldNumber = 2,
    kOneToAllFieldNumber = 3,
    kResetFieldNumber = 4,
  };
  // .esw.Walk walk = 1;
  bool has_walk() const;
  private:
  bool _internal_has_walk() const;
  public:
  void clear_walk();
  const ::esw::Walk& walk() const;
  ::esw::Walk* release_walk();
  ::esw::Walk* mutable_walk();
  void set_allocated_walk(::esw::Walk* walk);
  private:
  const ::esw::Walk& _internal_walk() const;
  ::esw::Walk* _internal_mutable_walk();
  public:
  void unsafe_arena_set_allocated_walk(
      ::esw::Walk* walk);
  ::esw::Walk* unsafe_arena_release_walk();

  // .esw.OneToOne oneToOne = 2;
  bool has_onetoone() const;
  private:
  bool _internal_has_onetoone() const;
  public:
  void clear_onetoone();
  const ::esw::OneToOne& onetoone() const;
  ::esw::OneToOne* release_onetoone();
  ::esw::OneToOne* mutable_onetoone();
  void set_allocated_onetoone(::esw::OneToOne* onetoone);
  private:
  const ::esw::OneToOne& _internal_onetoone() const;
  ::esw::OneToOne* _internal_mutable_onetoone();
  public:
  void unsafe_arena_set_allocated_onetoone(
      ::esw::OneToOne* onetoone);
  ::esw::OneToOne* unsafe_arena_release_onetoone();

  // .esw.OneToAll oneToAll = 3;
  bool has_onetoall() const;
  private:
  bool _internal_has_onetoall() const;
  public:
  void clear_onetoall();
  const ::esw::OneToAll& onetoall() const;
  ::esw::OneToAll* release_onetoall();
  ::esw::OneToAll* mutable_onetoall();
  void set_allocated_onetoall(::esw::OneToAll* onetoall);
  private:
  const ::esw::OneToAll& _internal_onetoall() const;
  ::esw::OneToAll* _internal_mutable_onetoall();
  public:
  void unsafe_arena_set_allocated_onetoall(
      ::esw::OneToAll* onetoall);
  ::esw::OneToAll* unsafe_arena_release_onetoall();

  // .esw.Reset reset = 4;
  bool has_reset() const;
  private:
  bool _internal_has_reset() const;
  public:
  void clear_reset();
  const ::esw::Reset& reset() const;
  ::esw::Reset* release_reset();
  ::esw::Reset* mutable_reset();
  void set_allocated_reset(::esw::Reset* reset);
  private:
  const ::esw::Reset& _internal_reset() const;
  ::esw::Reset* _internal_mutable_reset();
  public:
  void unsafe_arena_set_allocated_reset(
      ::esw::Reset* reset);
  ::esw::Reset* unsafe_arena_release_reset();

  void clear_msg();
  MsgCase msg_case() const;
  // @@protoc_insertion_point(class_scope:esw.Request)
 private:
  class _Internal;
  void set_has_walk();
  void set_has_onetoone();
  void set_has_onetoall();
  void set_has_reset();

  inline bool has_msg() const;
  inline void clear_has_msg();

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  union MsgUnion {
    MsgUnion() {}
    ::esw::Walk* walk_;
    ::esw::OneToOne* onetoone_;
    ::esw::OneToAll* onetoall_;
    ::esw::Reset* reset_;
  } msg_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  ::PROTOBUF_NAMESPACE_ID::uint32 _oneof_case_[1];

  friend struct ::TableStruct_scheme_2eproto;
};
// -------------------------------------------------------------------

class Walk PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:esw.Walk) */ {
 public:
  inline Walk() : Walk(nullptr) {};
  virtual ~Walk();

  Walk(const Walk& from);
  Walk(Walk&& from) noexcept
    : Walk() {
    *this = ::std::move(from);
  }

  inline Walk& operator=(const Walk& from) {
    CopyFrom(from);
    return *this;
  }
  inline Walk& operator=(Walk&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Walk& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Walk* internal_default_instance() {
    return reinterpret_cast<const Walk*>(
               &_Walk_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Walk& a, Walk& b) {
    a.Swap(&b);
  }
  inline void Swap(Walk* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Walk* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Walk* New() const final {
    return CreateMaybeMessage<Walk>(nullptr);
  }

  Walk* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Walk>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Walk& from);
  void MergeFrom(const Walk& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Walk* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "esw.Walk";
  }
  protected:
  explicit Walk(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_scheme_2eproto);
    return ::descriptor_table_scheme_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kLocationsFieldNumber = 1,
    kLengthsFieldNumber = 2,
  };
  // repeated .esw.Location locations = 1;
  int locations_size() const;
  private:
  int _internal_locations_size() const;
  public:
  void clear_locations();
  ::esw::Location* mutable_locations(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::esw::Location >*
      mutable_locations();
  private:
  const ::esw::Location& _internal_locations(int index) const;
  ::esw::Location* _internal_add_locations();
  public:
  const ::esw::Location& locations(int index) const;
  ::esw::Location* add_locations();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::esw::Location >&
      locations() const;

  // repeated uint32 lengths = 2;
  int lengths_size() const;
  private:
  int _internal_lengths_size() const;
  public:
  void clear_lengths();
  private:
  ::PROTOBUF_NAMESPACE_ID::uint32 _internal_lengths(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint32 >&
      _internal_lengths() const;
  void _internal_add_lengths(::PROTOBUF_NAMESPACE_ID::uint32 value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint32 >*
      _internal_mutable_lengths();
  public:
  ::PROTOBUF_NAMESPACE_ID::uint32 lengths(int index) const;
  void set_lengths(int index, ::PROTOBUF_NAMESPACE_ID::uint32 value);
  void add_lengths(::PROTOBUF_NAMESPACE_ID::uint32 value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint32 >&
      lengths() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint32 >*
      mutable_lengths();

  // @@protoc_insertion_point(class_scope:esw.Walk)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::esw::Location > locations_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint32 > lengths_;
  mutable std::atomic<int> _lengths_cached_byte_size_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_scheme_2eproto;
};
// -------------------------------------------------------------------

class OneToOne PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:esw.OneToOne) */ {
 public:
  inline OneToOne() : OneToOne(nullptr) {};
  virtual ~OneToOne();

  OneToOne(const OneToOne& from);
  OneToOne(OneToOne&& from) noexcept
    : OneToOne() {
    *this = ::std::move(from);
  }

  inline OneToOne& operator=(const OneToOne& from) {
    CopyFrom(from);
    return *this;
  }
  inline OneToOne& operator=(OneToOne&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const OneToOne& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const OneToOne* internal_default_instance() {
    return reinterpret_cast<const OneToOne*>(
               &_OneToOne_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(OneToOne& a, OneToOne& b) {
    a.Swap(&b);
  }
  inline void Swap(OneToOne* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(OneToOne* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline OneToOne* New() const final {
    return CreateMaybeMessage<OneToOne>(nullptr);
  }

  OneToOne* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<OneToOne>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const OneToOne& from);
  void MergeFrom(const OneToOne& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(OneToOne* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "esw.OneToOne";
  }
  protected:
  explicit OneToOne(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_scheme_2eproto);
    return ::descriptor_table_scheme_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kOriginFieldNumber = 1,
    kDestinationFieldNumber = 2,
  };
  // .esw.Location origin = 1;
  bool has_origin() const;
  private:
  bool _internal_has_origin() const;
  public:
  void clear_origin();
  const ::esw::Location& origin() const;
  ::esw::Location* release_origin();
  ::esw::Location* mutable_origin();
  void set_allocated_origin(::esw::Location* origin);
  private:
  const ::esw::Location& _internal_origin() const;
  ::esw::Location* _internal_mutable_origin();
  public:
  void unsafe_arena_set_allocated_origin(
      ::esw::Location* origin);
  ::esw::Location* unsafe_arena_release_origin();

  // .esw.Location destination = 2;
  bool has_destination() const;
  private:
  bool _internal_has_destination() const;
  public:
  void clear_destination();
  const ::esw::Location& destination() const;
  ::esw::Location* release_destination();
  ::esw::Location* mutable_destination();
  void set_allocated_destination(::esw::Location* destination);
  private:
  const ::esw::Location& _internal_destination() const;
  ::esw::Location* _internal_mutable_destination();
  public:
  void unsafe_arena_set_allocated_destination(
      ::esw::Location* destination);
  ::esw::Location* unsafe_arena_release_destination();

  // @@protoc_insertion_point(class_scope:esw.OneToOne)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::esw::Location* origin_;
  ::esw::Location* destination_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_scheme_2eproto;
};
// -------------------------------------------------------------------

class OneToAll PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:esw.OneToAll) */ {
 public:
  inline OneToAll() : OneToAll(nullptr) {};
  virtual ~OneToAll();

  OneToAll(const OneToAll& from);
  OneToAll(OneToAll&& from) noexcept
    : OneToAll() {
    *this = ::std::move(from);
  }

  inline OneToAll& operator=(const OneToAll& from) {
    CopyFrom(from);
    return *this;
  }
  inline OneToAll& operator=(OneToAll&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const OneToAll& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const OneToAll* internal_default_instance() {
    return reinterpret_cast<const OneToAll*>(
               &_OneToAll_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(OneToAll& a, OneToAll& b) {
    a.Swap(&b);
  }
  inline void Swap(OneToAll* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(OneToAll* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline OneToAll* New() const final {
    return CreateMaybeMessage<OneToAll>(nullptr);
  }

  OneToAll* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<OneToAll>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const OneToAll& from);
  void MergeFrom(const OneToAll& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(OneToAll* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "esw.OneToAll";
  }
  protected:
  explicit OneToAll(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_scheme_2eproto);
    return ::descriptor_table_scheme_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kOriginFieldNumber = 1,
  };
  // .esw.Location origin = 1;
  bool has_origin() const;
  private:
  bool _internal_has_origin() const;
  public:
  void clear_origin();
  const ::esw::Location& origin() const;
  ::esw::Location* release_origin();
  ::esw::Location* mutable_origin();
  void set_allocated_origin(::esw::Location* origin);
  private:
  const ::esw::Location& _internal_origin() const;
  ::esw::Location* _internal_mutable_origin();
  public:
  void unsafe_arena_set_allocated_origin(
      ::esw::Location* origin);
  ::esw::Location* unsafe_arena_release_origin();

  // @@protoc_insertion_point(class_scope:esw.OneToAll)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::esw::Location* origin_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_scheme_2eproto;
};
// -------------------------------------------------------------------

class Reset PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:esw.Reset) */ {
 public:
  inline Reset() : Reset(nullptr) {};
  virtual ~Reset();

  Reset(const Reset& from);
  Reset(Reset&& from) noexcept
    : Reset() {
    *this = ::std::move(from);
  }

  inline Reset& operator=(const Reset& from) {
    CopyFrom(from);
    return *this;
  }
  inline Reset& operator=(Reset&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Reset& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Reset* internal_default_instance() {
    return reinterpret_cast<const Reset*>(
               &_Reset_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    4;

  friend void swap(Reset& a, Reset& b) {
    a.Swap(&b);
  }
  inline void Swap(Reset* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Reset* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Reset* New() const final {
    return CreateMaybeMessage<Reset>(nullptr);
  }

  Reset* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Reset>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Reset& from);
  void MergeFrom(const Reset& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Reset* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "esw.Reset";
  }
  protected:
  explicit Reset(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_scheme_2eproto);
    return ::descriptor_table_scheme_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // @@protoc_insertion_point(class_scope:esw.Reset)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_scheme_2eproto;
};
// -------------------------------------------------------------------

class Location PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:esw.Location) */ {
 public:
  inline Location() : Location(nullptr) {};
  virtual ~Location();

  Location(const Location& from);
  Location(Location&& from) noexcept
    : Location() {
    *this = ::std::move(from);
  }

  inline Location& operator=(const Location& from) {
    CopyFrom(from);
    return *this;
  }
  inline Location& operator=(Location&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Location& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Location* internal_default_instance() {
    return reinterpret_cast<const Location*>(
               &_Location_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    5;

  friend void swap(Location& a, Location& b) {
    a.Swap(&b);
  }
  inline void Swap(Location* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Location* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Location* New() const final {
    return CreateMaybeMessage<Location>(nullptr);
  }

  Location* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Location>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Location& from);
  void MergeFrom(const Location& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Location* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "esw.Location";
  }
  protected:
  explicit Location(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_scheme_2eproto);
    return ::descriptor_table_scheme_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kXFieldNumber = 1,
    kYFieldNumber = 2,
  };
  // int32 x = 1;
  void clear_x();
  ::PROTOBUF_NAMESPACE_ID::int32 x() const;
  void set_x(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_x() const;
  void _internal_set_x(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // int32 y = 2;
  void clear_y();
  ::PROTOBUF_NAMESPACE_ID::int32 y() const;
  void set_y(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_y() const;
  void _internal_set_y(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:esw.Location)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::int32 x_;
  ::PROTOBUF_NAMESPACE_ID::int32 y_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_scheme_2eproto;
};
// -------------------------------------------------------------------

class Response PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:esw.Response) */ {
 public:
  inline Response() : Response(nullptr) {};
  virtual ~Response();

  Response(const Response& from);
  Response(Response&& from) noexcept
    : Response() {
    *this = ::std::move(from);
  }

  inline Response& operator=(const Response& from) {
    CopyFrom(from);
    return *this;
  }
  inline Response& operator=(Response&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Response& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Response* internal_default_instance() {
    return reinterpret_cast<const Response*>(
               &_Response_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    6;

  friend void swap(Response& a, Response& b) {
    a.Swap(&b);
  }
  inline void Swap(Response* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Response* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Response* New() const final {
    return CreateMaybeMessage<Response>(nullptr);
  }

  Response* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Response>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Response& from);
  void MergeFrom(const Response& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Response* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "esw.Response";
  }
  protected:
  explicit Response(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_scheme_2eproto);
    return ::descriptor_table_scheme_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  typedef Response_Status Status;
  static constexpr Status OK =
    Response_Status_OK;
  static constexpr Status ERROR =
    Response_Status_ERROR;
  static inline bool Status_IsValid(int value) {
    return Response_Status_IsValid(value);
  }
  static constexpr Status Status_MIN =
    Response_Status_Status_MIN;
  static constexpr Status Status_MAX =
    Response_Status_Status_MAX;
  static constexpr int Status_ARRAYSIZE =
    Response_Status_Status_ARRAYSIZE;
  static inline const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor*
  Status_descriptor() {
    return Response_Status_descriptor();
  }
  template<typename T>
  static inline const std::string& Status_Name(T enum_t_value) {
    static_assert(::std::is_same<T, Status>::value ||
      ::std::is_integral<T>::value,
      "Incorrect type passed to function Status_Name.");
    return Response_Status_Name(enum_t_value);
  }
  static inline bool Status_Parse(const std::string& name,
      Status* value) {
    return Response_Status_Parse(name, value);
  }

  // accessors -------------------------------------------------------

  enum : int {
    kErrMsgFieldNumber = 2,
    kShortestPathLengthFieldNumber = 3,
    kTotalLengthFieldNumber = 4,
    kStatusFieldNumber = 1,
  };
  // string errMsg = 2;
  void clear_errmsg();
  const std::string& errmsg() const;
  void set_errmsg(const std::string& value);
  void set_errmsg(std::string&& value);
  void set_errmsg(const char* value);
  void set_errmsg(const char* value, size_t size);
  std::string* mutable_errmsg();
  std::string* release_errmsg();
  void set_allocated_errmsg(std::string* errmsg);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_errmsg();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_errmsg(
      std::string* errmsg);
  private:
  const std::string& _internal_errmsg() const;
  void _internal_set_errmsg(const std::string& value);
  std::string* _internal_mutable_errmsg();
  public:

  // uint64 shortest_path_length = 3;
  void clear_shortest_path_length();
  ::PROTOBUF_NAMESPACE_ID::uint64 shortest_path_length() const;
  void set_shortest_path_length(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_shortest_path_length() const;
  void _internal_set_shortest_path_length(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // uint64 total_length = 4;
  void clear_total_length();
  ::PROTOBUF_NAMESPACE_ID::uint64 total_length() const;
  void set_total_length(::PROTOBUF_NAMESPACE_ID::uint64 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::uint64 _internal_total_length() const;
  void _internal_set_total_length(::PROTOBUF_NAMESPACE_ID::uint64 value);
  public:

  // .esw.Response.Status status = 1;
  void clear_status();
  ::esw::Response_Status status() const;
  void set_status(::esw::Response_Status value);
  private:
  ::esw::Response_Status _internal_status() const;
  void _internal_set_status(::esw::Response_Status value);
  public:

  // @@protoc_insertion_point(class_scope:esw.Response)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr errmsg_;
  ::PROTOBUF_NAMESPACE_ID::uint64 shortest_path_length_;
  ::PROTOBUF_NAMESPACE_ID::uint64 total_length_;
  int status_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_scheme_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Request

// .esw.Walk walk = 1;
inline bool Request::_internal_has_walk() const {
  return msg_case() == kWalk;
}
inline bool Request::has_walk() const {
  return _internal_has_walk();
}
inline void Request::set_has_walk() {
  _oneof_case_[0] = kWalk;
}
inline void Request::clear_walk() {
  if (_internal_has_walk()) {
    if (GetArena() == nullptr) {
      delete msg_.walk_;
    }
    clear_has_msg();
  }
}
inline ::esw::Walk* Request::release_walk() {
  // @@protoc_insertion_point(field_release:esw.Request.walk)
  if (_internal_has_walk()) {
    clear_has_msg();
      ::esw::Walk* temp = msg_.walk_;
    if (GetArena() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    msg_.walk_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::esw::Walk& Request::_internal_walk() const {
  return _internal_has_walk()
      ? *msg_.walk_
      : *reinterpret_cast< ::esw::Walk*>(&::esw::_Walk_default_instance_);
}
inline const ::esw::Walk& Request::walk() const {
  // @@protoc_insertion_point(field_get:esw.Request.walk)
  return _internal_walk();
}
inline ::esw::Walk* Request::unsafe_arena_release_walk() {
  // @@protoc_insertion_point(field_unsafe_arena_release:esw.Request.walk)
  if (_internal_has_walk()) {
    clear_has_msg();
    ::esw::Walk* temp = msg_.walk_;
    msg_.walk_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void Request::unsafe_arena_set_allocated_walk(::esw::Walk* walk) {
  clear_msg();
  if (walk) {
    set_has_walk();
    msg_.walk_ = walk;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:esw.Request.walk)
}
inline ::esw::Walk* Request::_internal_mutable_walk() {
  if (!_internal_has_walk()) {
    clear_msg();
    set_has_walk();
    msg_.walk_ = CreateMaybeMessage< ::esw::Walk >(GetArena());
  }
  return msg_.walk_;
}
inline ::esw::Walk* Request::mutable_walk() {
  // @@protoc_insertion_point(field_mutable:esw.Request.walk)
  return _internal_mutable_walk();
}

// .esw.OneToOne oneToOne = 2;
inline bool Request::_internal_has_onetoone() const {
  return msg_case() == kOneToOne;
}
inline bool Request::has_onetoone() const {
  return _internal_has_onetoone();
}
inline void Request::set_has_onetoone() {
  _oneof_case_[0] = kOneToOne;
}
inline void Request::clear_onetoone() {
  if (_internal_has_onetoone()) {
    if (GetArena() == nullptr) {
      delete msg_.onetoone_;
    }
    clear_has_msg();
  }
}
inline ::esw::OneToOne* Request::release_onetoone() {
  // @@protoc_insertion_point(field_release:esw.Request.oneToOne)
  if (_internal_has_onetoone()) {
    clear_has_msg();
      ::esw::OneToOne* temp = msg_.onetoone_;
    if (GetArena() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    msg_.onetoone_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::esw::OneToOne& Request::_internal_onetoone() const {
  return _internal_has_onetoone()
      ? *msg_.onetoone_
      : *reinterpret_cast< ::esw::OneToOne*>(&::esw::_OneToOne_default_instance_);
}
inline const ::esw::OneToOne& Request::onetoone() const {
  // @@protoc_insertion_point(field_get:esw.Request.oneToOne)
  return _internal_onetoone();
}
inline ::esw::OneToOne* Request::unsafe_arena_release_onetoone() {
  // @@protoc_insertion_point(field_unsafe_arena_release:esw.Request.oneToOne)
  if (_internal_has_onetoone()) {
    clear_has_msg();
    ::esw::OneToOne* temp = msg_.onetoone_;
    msg_.onetoone_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void Request::unsafe_arena_set_allocated_onetoone(::esw::OneToOne* onetoone) {
  clear_msg();
  if (onetoone) {
    set_has_onetoone();
    msg_.onetoone_ = onetoone;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:esw.Request.oneToOne)
}
inline ::esw::OneToOne* Request::_internal_mutable_onetoone() {
  if (!_internal_has_onetoone()) {
    clear_msg();
    set_has_onetoone();
    msg_.onetoone_ = CreateMaybeMessage< ::esw::OneToOne >(GetArena());
  }
  return msg_.onetoone_;
}
inline ::esw::OneToOne* Request::mutable_onetoone() {
  // @@protoc_insertion_point(field_mutable:esw.Request.oneToOne)
  return _internal_mutable_onetoone();
}

// .esw.OneToAll oneToAll = 3;
inline bool Request::_internal_has_onetoall() const {
  return msg_case() == kOneToAll;
}
inline bool Request::has_onetoall() const {
  return _internal_has_onetoall();
}
inline void Request::set_has_onetoall() {
  _oneof_case_[0] = kOneToAll;
}
inline void Request::clear_onetoall() {
  if (_internal_has_onetoall()) {
    if (GetArena() == nullptr) {
      delete msg_.onetoall_;
    }
    clear_has_msg();
  }
}
inline ::esw::OneToAll* Request::release_onetoall() {
  // @@protoc_insertion_point(field_release:esw.Request.oneToAll)
  if (_internal_has_onetoall()) {
    clear_has_msg();
      ::esw::OneToAll* temp = msg_.onetoall_;
    if (GetArena() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    msg_.onetoall_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::esw::OneToAll& Request::_internal_onetoall() const {
  return _internal_has_onetoall()
      ? *msg_.onetoall_
      : *reinterpret_cast< ::esw::OneToAll*>(&::esw::_OneToAll_default_instance_);
}
inline const ::esw::OneToAll& Request::onetoall() const {
  // @@protoc_insertion_point(field_get:esw.Request.oneToAll)
  return _internal_onetoall();
}
inline ::esw::OneToAll* Request::unsafe_arena_release_onetoall() {
  // @@protoc_insertion_point(field_unsafe_arena_release:esw.Request.oneToAll)
  if (_internal_has_onetoall()) {
    clear_has_msg();
    ::esw::OneToAll* temp = msg_.onetoall_;
    msg_.onetoall_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void Request::unsafe_arena_set_allocated_onetoall(::esw::OneToAll* onetoall) {
  clear_msg();
  if (onetoall) {
    set_has_onetoall();
    msg_.onetoall_ = onetoall;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:esw.Request.oneToAll)
}
inline ::esw::OneToAll* Request::_internal_mutable_onetoall() {
  if (!_internal_has_onetoall()) {
    clear_msg();
    set_has_onetoall();
    msg_.onetoall_ = CreateMaybeMessage< ::esw::OneToAll >(GetArena());
  }
  return msg_.onetoall_;
}
inline ::esw::OneToAll* Request::mutable_onetoall() {
  // @@protoc_insertion_point(field_mutable:esw.Request.oneToAll)
  return _internal_mutable_onetoall();
}

// .esw.Reset reset = 4;
inline bool Request::_internal_has_reset() const {
  return msg_case() == kReset;
}
inline bool Request::has_reset() const {
  return _internal_has_reset();
}
inline void Request::set_has_reset() {
  _oneof_case_[0] = kReset;
}
inline void Request::clear_reset() {
  if (_internal_has_reset()) {
    if (GetArena() == nullptr) {
      delete msg_.reset_;
    }
    clear_has_msg();
  }
}
inline ::esw::Reset* Request::release_reset() {
  // @@protoc_insertion_point(field_release:esw.Request.reset)
  if (_internal_has_reset()) {
    clear_has_msg();
      ::esw::Reset* temp = msg_.reset_;
    if (GetArena() != nullptr) {
      temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
    }
    msg_.reset_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline const ::esw::Reset& Request::_internal_reset() const {
  return _internal_has_reset()
      ? *msg_.reset_
      : *reinterpret_cast< ::esw::Reset*>(&::esw::_Reset_default_instance_);
}
inline const ::esw::Reset& Request::reset() const {
  // @@protoc_insertion_point(field_get:esw.Request.reset)
  return _internal_reset();
}
inline ::esw::Reset* Request::unsafe_arena_release_reset() {
  // @@protoc_insertion_point(field_unsafe_arena_release:esw.Request.reset)
  if (_internal_has_reset()) {
    clear_has_msg();
    ::esw::Reset* temp = msg_.reset_;
    msg_.reset_ = nullptr;
    return temp;
  } else {
    return nullptr;
  }
}
inline void Request::unsafe_arena_set_allocated_reset(::esw::Reset* reset) {
  clear_msg();
  if (reset) {
    set_has_reset();
    msg_.reset_ = reset;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:esw.Request.reset)
}
inline ::esw::Reset* Request::_internal_mutable_reset() {
  if (!_internal_has_reset()) {
    clear_msg();
    set_has_reset();
    msg_.reset_ = CreateMaybeMessage< ::esw::Reset >(GetArena());
  }
  return msg_.reset_;
}
inline ::esw::Reset* Request::mutable_reset() {
  // @@protoc_insertion_point(field_mutable:esw.Request.reset)
  return _internal_mutable_reset();
}

inline bool Request::has_msg() const {
  return msg_case() != MSG_NOT_SET;
}
inline void Request::clear_has_msg() {
  _oneof_case_[0] = MSG_NOT_SET;
}
inline Request::MsgCase Request::msg_case() const {
  return Request::MsgCase(_oneof_case_[0]);
}
// -------------------------------------------------------------------

// Walk

// repeated .esw.Location locations = 1;
inline int Walk::_internal_locations_size() const {
  return locations_.size();
}
inline int Walk::locations_size() const {
  return _internal_locations_size();
}
inline void Walk::clear_locations() {
  locations_.Clear();
}
inline ::esw::Location* Walk::mutable_locations(int index) {
  // @@protoc_insertion_point(field_mutable:esw.Walk.locations)
  return locations_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::esw::Location >*
Walk::mutable_locations() {
  // @@protoc_insertion_point(field_mutable_list:esw.Walk.locations)
  return &locations_;
}
inline const ::esw::Location& Walk::_internal_locations(int index) const {
  return locations_.Get(index);
}
inline const ::esw::Location& Walk::locations(int index) const {
  // @@protoc_insertion_point(field_get:esw.Walk.locations)
  return _internal_locations(index);
}
inline ::esw::Location* Walk::_internal_add_locations() {
  return locations_.Add();
}
inline ::esw::Location* Walk::add_locations() {
  // @@protoc_insertion_point(field_add:esw.Walk.locations)
  return _internal_add_locations();
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::esw::Location >&
Walk::locations() const {
  // @@protoc_insertion_point(field_list:esw.Walk.locations)
  return locations_;
}

// repeated uint32 lengths = 2;
inline int Walk::_internal_lengths_size() const {
  return lengths_.size();
}
inline int Walk::lengths_size() const {
  return _internal_lengths_size();
}
inline void Walk::clear_lengths() {
  lengths_.Clear();
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Walk::_internal_lengths(int index) const {
  return lengths_.Get(index);
}
inline ::PROTOBUF_NAMESPACE_ID::uint32 Walk::lengths(int index) const {
  // @@protoc_insertion_point(field_get:esw.Walk.lengths)
  return _internal_lengths(index);
}
inline void Walk::set_lengths(int index, ::PROTOBUF_NAMESPACE_ID::uint32 value) {
  lengths_.Set(index, value);
  // @@protoc_insertion_point(field_set:esw.Walk.lengths)
}
inline void Walk::_internal_add_lengths(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  lengths_.Add(value);
}
inline void Walk::add_lengths(::PROTOBUF_NAMESPACE_ID::uint32 value) {
  _internal_add_lengths(value);
  // @@protoc_insertion_point(field_add:esw.Walk.lengths)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint32 >&
Walk::_internal_lengths() const {
  return lengths_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint32 >&
Walk::lengths() const {
  // @@protoc_insertion_point(field_list:esw.Walk.lengths)
  return _internal_lengths();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint32 >*
Walk::_internal_mutable_lengths() {
  return &lengths_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< ::PROTOBUF_NAMESPACE_ID::uint32 >*
Walk::mutable_lengths() {
  // @@protoc_insertion_point(field_mutable_list:esw.Walk.lengths)
  return _internal_mutable_lengths();
}

// -------------------------------------------------------------------

// OneToOne

// .esw.Location origin = 1;
inline bool OneToOne::_internal_has_origin() const {
  return this != internal_default_instance() && origin_ != nullptr;
}
inline bool OneToOne::has_origin() const {
  return _internal_has_origin();
}
inline void OneToOne::clear_origin() {
  if (GetArena() == nullptr && origin_ != nullptr) {
    delete origin_;
  }
  origin_ = nullptr;
}
inline const ::esw::Location& OneToOne::_internal_origin() const {
  const ::esw::Location* p = origin_;
  return p != nullptr ? *p : *reinterpret_cast<const ::esw::Location*>(
      &::esw::_Location_default_instance_);
}
inline const ::esw::Location& OneToOne::origin() const {
  // @@protoc_insertion_point(field_get:esw.OneToOne.origin)
  return _internal_origin();
}
inline void OneToOne::unsafe_arena_set_allocated_origin(
    ::esw::Location* origin) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(origin_);
  }
  origin_ = origin;
  if (origin) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:esw.OneToOne.origin)
}
inline ::esw::Location* OneToOne::release_origin() {
  auto temp = unsafe_arena_release_origin();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::esw::Location* OneToOne::unsafe_arena_release_origin() {
  // @@protoc_insertion_point(field_release:esw.OneToOne.origin)
  
  ::esw::Location* temp = origin_;
  origin_ = nullptr;
  return temp;
}
inline ::esw::Location* OneToOne::_internal_mutable_origin() {
  
  if (origin_ == nullptr) {
    auto* p = CreateMaybeMessage<::esw::Location>(GetArena());
    origin_ = p;
  }
  return origin_;
}
inline ::esw::Location* OneToOne::mutable_origin() {
  // @@protoc_insertion_point(field_mutable:esw.OneToOne.origin)
  return _internal_mutable_origin();
}
inline void OneToOne::set_allocated_origin(::esw::Location* origin) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete origin_;
  }
  if (origin) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(origin);
    if (message_arena != submessage_arena) {
      origin = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, origin, submessage_arena);
    }
    
  } else {
    
  }
  origin_ = origin;
  // @@protoc_insertion_point(field_set_allocated:esw.OneToOne.origin)
}

// .esw.Location destination = 2;
inline bool OneToOne::_internal_has_destination() const {
  return this != internal_default_instance() && destination_ != nullptr;
}
inline bool OneToOne::has_destination() const {
  return _internal_has_destination();
}
inline void OneToOne::clear_destination() {
  if (GetArena() == nullptr && destination_ != nullptr) {
    delete destination_;
  }
  destination_ = nullptr;
}
inline const ::esw::Location& OneToOne::_internal_destination() const {
  const ::esw::Location* p = destination_;
  return p != nullptr ? *p : *reinterpret_cast<const ::esw::Location*>(
      &::esw::_Location_default_instance_);
}
inline const ::esw::Location& OneToOne::destination() const {
  // @@protoc_insertion_point(field_get:esw.OneToOne.destination)
  return _internal_destination();
}
inline void OneToOne::unsafe_arena_set_allocated_destination(
    ::esw::Location* destination) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(destination_);
  }
  destination_ = destination;
  if (destination) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:esw.OneToOne.destination)
}
inline ::esw::Location* OneToOne::release_destination() {
  auto temp = unsafe_arena_release_destination();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::esw::Location* OneToOne::unsafe_arena_release_destination() {
  // @@protoc_insertion_point(field_release:esw.OneToOne.destination)
  
  ::esw::Location* temp = destination_;
  destination_ = nullptr;
  return temp;
}
inline ::esw::Location* OneToOne::_internal_mutable_destination() {
  
  if (destination_ == nullptr) {
    auto* p = CreateMaybeMessage<::esw::Location>(GetArena());
    destination_ = p;
  }
  return destination_;
}
inline ::esw::Location* OneToOne::mutable_destination() {
  // @@protoc_insertion_point(field_mutable:esw.OneToOne.destination)
  return _internal_mutable_destination();
}
inline void OneToOne::set_allocated_destination(::esw::Location* destination) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete destination_;
  }
  if (destination) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(destination);
    if (message_arena != submessage_arena) {
      destination = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, destination, submessage_arena);
    }
    
  } else {
    
  }
  destination_ = destination;
  // @@protoc_insertion_point(field_set_allocated:esw.OneToOne.destination)
}

// -------------------------------------------------------------------

// OneToAll

// .esw.Location origin = 1;
inline bool OneToAll::_internal_has_origin() const {
  return this != internal_default_instance() && origin_ != nullptr;
}
inline bool OneToAll::has_origin() const {
  return _internal_has_origin();
}
inline void OneToAll::clear_origin() {
  if (GetArena() == nullptr && origin_ != nullptr) {
    delete origin_;
  }
  origin_ = nullptr;
}
inline const ::esw::Location& OneToAll::_internal_origin() const {
  const ::esw::Location* p = origin_;
  return p != nullptr ? *p : *reinterpret_cast<const ::esw::Location*>(
      &::esw::_Location_default_instance_);
}
inline const ::esw::Location& OneToAll::origin() const {
  // @@protoc_insertion_point(field_get:esw.OneToAll.origin)
  return _internal_origin();
}
inline void OneToAll::unsafe_arena_set_allocated_origin(
    ::esw::Location* origin) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(origin_);
  }
  origin_ = origin;
  if (origin) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:esw.OneToAll.origin)
}
inline ::esw::Location* OneToAll::release_origin() {
  auto temp = unsafe_arena_release_origin();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::esw::Location* OneToAll::unsafe_arena_release_origin() {
  // @@protoc_insertion_point(field_release:esw.OneToAll.origin)
  
  ::esw::Location* temp = origin_;
  origin_ = nullptr;
  return temp;
}
inline ::esw::Location* OneToAll::_internal_mutable_origin() {
  
  if (origin_ == nullptr) {
    auto* p = CreateMaybeMessage<::esw::Location>(GetArena());
    origin_ = p;
  }
  return origin_;
}
inline ::esw::Location* OneToAll::mutable_origin() {
  // @@protoc_insertion_point(field_mutable:esw.OneToAll.origin)
  return _internal_mutable_origin();
}
inline void OneToAll::set_allocated_origin(::esw::Location* origin) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete origin_;
  }
  if (origin) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(origin);
    if (message_arena != submessage_arena) {
      origin = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, origin, submessage_arena);
    }
    
  } else {
    
  }
  origin_ = origin;
  // @@protoc_insertion_point(field_set_allocated:esw.OneToAll.origin)
}

// -------------------------------------------------------------------

// Reset

// -------------------------------------------------------------------

// Location

// int32 x = 1;
inline void Location::clear_x() {
  x_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Location::_internal_x() const {
  return x_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Location::x() const {
  // @@protoc_insertion_point(field_get:esw.Location.x)
  return _internal_x();
}
inline void Location::_internal_set_x(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  x_ = value;
}
inline void Location::set_x(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:esw.Location.x)
}

// int32 y = 2;
inline void Location::clear_y() {
  y_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Location::_internal_y() const {
  return y_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Location::y() const {
  // @@protoc_insertion_point(field_get:esw.Location.y)
  return _internal_y();
}
inline void Location::_internal_set_y(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  y_ = value;
}
inline void Location::set_y(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:esw.Location.y)
}

// -------------------------------------------------------------------

// Response

// .esw.Response.Status status = 1;
inline void Response::clear_status() {
  status_ = 0;
}
inline ::esw::Response_Status Response::_internal_status() const {
  return static_cast< ::esw::Response_Status >(status_);
}
inline ::esw::Response_Status Response::status() const {
  // @@protoc_insertion_point(field_get:esw.Response.status)
  return _internal_status();
}
inline void Response::_internal_set_status(::esw::Response_Status value) {
  
  status_ = value;
}
inline void Response::set_status(::esw::Response_Status value) {
  _internal_set_status(value);
  // @@protoc_insertion_point(field_set:esw.Response.status)
}

// string errMsg = 2;
inline void Response::clear_errmsg() {
  errmsg_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& Response::errmsg() const {
  // @@protoc_insertion_point(field_get:esw.Response.errMsg)
  return _internal_errmsg();
}
inline void Response::set_errmsg(const std::string& value) {
  _internal_set_errmsg(value);
  // @@protoc_insertion_point(field_set:esw.Response.errMsg)
}
inline std::string* Response::mutable_errmsg() {
  // @@protoc_insertion_point(field_mutable:esw.Response.errMsg)
  return _internal_mutable_errmsg();
}
inline const std::string& Response::_internal_errmsg() const {
  return errmsg_.Get();
}
inline void Response::_internal_set_errmsg(const std::string& value) {
  
  errmsg_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void Response::set_errmsg(std::string&& value) {
  
  errmsg_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:esw.Response.errMsg)
}
inline void Response::set_errmsg(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  errmsg_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:esw.Response.errMsg)
}
inline void Response::set_errmsg(const char* value,
    size_t size) {
  
  errmsg_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:esw.Response.errMsg)
}
inline std::string* Response::_internal_mutable_errmsg() {
  
  return errmsg_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* Response::release_errmsg() {
  // @@protoc_insertion_point(field_release:esw.Response.errMsg)
  return errmsg_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void Response::set_allocated_errmsg(std::string* errmsg) {
  if (errmsg != nullptr) {
    
  } else {
    
  }
  errmsg_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), errmsg,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:esw.Response.errMsg)
}
inline std::string* Response::unsafe_arena_release_errmsg() {
  // @@protoc_insertion_point(field_unsafe_arena_release:esw.Response.errMsg)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return errmsg_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void Response::unsafe_arena_set_allocated_errmsg(
    std::string* errmsg) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (errmsg != nullptr) {
    
  } else {
    
  }
  errmsg_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      errmsg, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:esw.Response.errMsg)
}

// uint64 shortest_path_length = 3;
inline void Response::clear_shortest_path_length() {
  shortest_path_length_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 Response::_internal_shortest_path_length() const {
  return shortest_path_length_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 Response::shortest_path_length() const {
  // @@protoc_insertion_point(field_get:esw.Response.shortest_path_length)
  return _internal_shortest_path_length();
}
inline void Response::_internal_set_shortest_path_length(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  shortest_path_length_ = value;
}
inline void Response::set_shortest_path_length(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_shortest_path_length(value);
  // @@protoc_insertion_point(field_set:esw.Response.shortest_path_length)
}

// uint64 total_length = 4;
inline void Response::clear_total_length() {
  total_length_ = PROTOBUF_ULONGLONG(0);
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 Response::_internal_total_length() const {
  return total_length_;
}
inline ::PROTOBUF_NAMESPACE_ID::uint64 Response::total_length() const {
  // @@protoc_insertion_point(field_get:esw.Response.total_length)
  return _internal_total_length();
}
inline void Response::_internal_set_total_length(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  
  total_length_ = value;
}
inline void Response::set_total_length(::PROTOBUF_NAMESPACE_ID::uint64 value) {
  _internal_set_total_length(value);
  // @@protoc_insertion_point(field_set:esw.Response.total_length)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace esw

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::esw::Response_Status> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::esw::Response_Status>() {
  return ::esw::Response_Status_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_scheme_2eproto
